drop table if exists items;
drop table if exists members;

create table members (
    id bigint generated by default as identity primary key,
    login_id varchar(50) not null unique,
    name varchar(50) not null,
    password varchar(100) not null
);

create table items (
    id bigint generated by default as identity primary key,
    title varchar(100) not null,
    description varchar(1000),
    price integer not null,
    status varchar(20) not null,
    seller_id bigint
);
